import os, json, time, re, collections
from pathlib import Path
from typing import Dict, Any

STOPWORDS = set("""a an the and or of to in is it this that with for on as at be by from are was were will would could should you your i me my we our they them their he she his her
do does did doing done have has had having so just not can't cannot don't won't what's who's it's
""".split())

def _extract_text(file_path: Path) -> str:
    # Minimal extractor: if it's a .txt use its content; otherwise return a fixed placeholder
    if file_path.suffix.lower() == ".txt":
        return file_path.read_text(encoding="utf-8", errors="ignore")
    return "This is a demo placeholder transcript generated by the mock pipeline."

def _keywords(text: str, k: int = 8):
    tokens = [t.lower() for t in re.findall(r"\b\w+\b", text)]
    tokens = [t for t in tokens if t not in STOPWORDS and len(t) > 2]
    counts = collections.Counter(tokens)
    return [w for w, _ in counts.most_common(k)]

def _sentiment(text: str) -> str:
    # Ultra naive rule-based sentiment so the demo works offline
    low = text.lower()
    if any(w in low for w in ["excellent", "great", "love", "amazing", "good", "success"]):
        return "positive"
    if any(w in low for w in ["terrible", "bad", "bug", "issue", "fail", "hate"]):
        return "negative"
    return "neutral"

def process_job(job_id: str, input_path: Path, output_dir: Path) -> Dict[str, Any]:
    # Simulate work
    time.sleep(0.5)

    text = _extract_text(input_path)
    words = re.findall(r"\b\w+\b", text)
    unique = set(w.lower() for w in words)
    top_kw = _keywords(text, k=8)
    sent = _sentiment(text)

    # A deterministic "summary" for offline demo
    summary = f"{len(words)} words, {len(unique)} unique. Sentiment: {sent}. Top keywords: {', '.join(top_kw)}."

    insights = {
        "job_id": job_id,
        "summary": summary,
        "metrics": {
            "word_count": len(words),
            "unique_words": len(unique),
            "sentiment": sent,
            "top_keywords": top_kw,
        },
        "transcript_preview": text[:500],
        "provider": "mock",
    }

    out_file = output_dir / "insights.json"
    out_file.write_text(json.dumps(insights, ensure_ascii=False, indent=2), encoding="utf-8")
    return insights
